version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: intl-messageformat
    versions:
    - 9.4.3
    - 9.4.6
    - 9.4.9
    - 9.5.2
    - 9.5.3
    - 9.6.3
  - dependency-name: react-select
    versions:
    - 4.0.2
    - 4.1.0
    - 4.2.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.5
    - 7.13.10
    - 7.13.9
  - dependency-name: react-textarea-autosize
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
